# Use an official lightweight Node.js image.
FROM node:18-alpine

WORKDIR /app

# Install dependencies.
COPY package.json  package-lock.json  ./


RUN npm ci --legacy-peer-deps


# Copy all source code.
COPY . .

# Expose the development port.
EXPOSE 3000

# Start Next.js in development mode.
CMD ["npm", "run", "dev"]
